[package]
name = "scgi"
version = "0.3.0"
authors = ["ArtemGr <artemciy@gmail.com>"]

description = "Simple SCGI parser"
documentation = "http://www.rust-ci.org/ArtemGr/rust-scgi/doc/scgi/"
repository = "https://github.com/ArtemGr/rust-scgi"
readme = "README.md"
keywords = ["web", "server"]
license = "MIT"

[lib]
name = "scgi"
path = "src/scgi.rs"
doctest = false

[[bin]]
name = "example"
path = "examples/example.rs"
doctest = false
bench = false

[dependencies]
bufstream = "0.1"
